version: '3.8'

services:
  # Frontend (Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
        - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "80:80"

  # Backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - API_ENDPOINT=${API_ENDPOINT:-""}
      - API_KEY=${API_KEY:-""}
