version: '3.8'

services:
  # Frontend (Vite Dev Server)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "80:5000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - API_ENDPOINT=${API_ENDPOINT:-""}
      - API_KEY=${API_KEY:-""}
